<?php
$this->doctype(\Zend\View\Helper\Doctype::HTML5);
$this->headMeta()->setCharset('UTF-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');

$this->headLink()->appendStylesheet(
    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css'
);

$this->headScript()->appendFile(
    'https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js',
    'text/javascript'
);

$this->headScript()->appendFile(
    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js',
    'text/javascript'
);

$this->headLink()->prependStylesheet(
    $this->basePath().'/modules/installer/css/style.css'
);

$this->headLink()->prependStylesheet(
    $this->basePath().'/modules/installer/css/bootstrap-theme.min.css'
);


?>
<html>
<head>
    <title>R-Writer Installer</title>
    <?= $this->headMeta(); ?>
    <?= $this->headScript(); ?>
    <?= $this->headLink(); ?>
</head>
<body>

<div class="container">
    <div class="row" id="install_header">
        <div class="col-md-3">
            <img src="/logo.jpg" />
        </div>
    </div>

    <div class="row" id="install_nav_bar">
        <div class="col-md-12">&nbsp;</div>
    </div>

    <div class="row" id="install_body">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8">
            <?= $this->content ?>
        </div>
        <div class="col-lg-2">&nbsp;</div>
    </div>

    <div class="row" id="install_footer">
        <div class="col-md-12">Footer</div>
    </div>

</div>
</body>
</html>
