<h2>Welcome</h2>

<p>
    Lorem ipsum dolor sit amet, adhuc antiopam partiendo id pri, veri temporibus instructior has at.
    Cu nam luptatum conclusionemque, ad vix facete fabellas contentiones, cu lorem quaestio pri.
    Eam oratio gubergren eu, brute mucius ad ius. Eam at feugait fuisset atomorum. Pri ea eius denique,
    instructior necessitatibus pri te. No pro eros philosophia, no erat civibus suscipit usu, paulo
    ignota an vim.
</p>
<p>
    Nec ei amet esse. Cu qui iriure singulis senserit. Ne minim tamquam pro, duo no partem graeci
    accumsan, mel populo civibus concludaturque ne. Pri graece persequeris instructior cu.
</p>
<p>
    Ex pri alia enim adolescens. Illud quaeque ut vis. Ad consulatu similique vix, ex duo option
    menandri, ea assum legendos eum. Quas nostrud no mei, quaeque honestatis vis et. Mel alia
    tacimates cu.
</p>
<p>
    Erant graecis ne has. Cu mea facilisi philosophia, pri illum veniam volutpat ad, etiam quando
    cu eos. Ea sit rebum antiopam deseruisse, id case facilis expetendis per. Eripuit equidem
    accusata eam ei, vix assum melius ea.
</p>
<p>
    Timeam noluisse tractatos an cum, sea clita latine et, eum illud impetus partiendo ea. Eum ut
    natum delicata, qui te atqui corrumpit abhorreant, pri eruditi salutandi democritum no. Et
    facete principes est, at sea zril eripuit. Deseruisse neglegentur philosophia cum no. Et sea
    noluisse volutpat eloquentiam, ne odio ornatus usu, amet sanctus concludaturque mea cu.
</p>
<p>&nbsp;</p>
<div>
    <a href="<?= $this->url('installer:welcome', ['action' => 'system-check']) ?>" class="btn btn-success">Next </a>
</div>