<?php
$this->headLink()->prependStylesheet(
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'
);

//$this->inlineScript()->prependFile(
//    '/bower-asset/jquery/dist/jquery.min.js'
//);
//
//$this->inlineScript()->appendFile(
//    '/bower-asset/tether/dist/tether.min.js'
//);

$this->inlineScript()->appendFile(
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'
);

$this->headLink()->prependStylesheet(
    '/modules/blazon/install/css/style.css'
);

//$this->headMeta()->setCharset('UTF-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');


?>
<html>
<head>
    <title>R-Writer Installer</title>
    <script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
    <?= $this->headMeta(); ?>
    <?= $this->headScript(); ?>
    <?= $this->headLink(); ?>
</head>
<body>
<div class="container">
    <div class="row" id="install_header">
        <div class="col-md-3">
            <img src="/modules/blazon/install/image/logo_web.jpg" />
        </div>
    </div>

    <div class="row" id="install_nav_bar">
        <div class="col-md-12">&nbsp;</div>
    </div>

    <div class="row" id="install_body">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8">
            <?= $this->content ?>
        </div>
        <div class="col-lg-2">&nbsp;</div>
    </div>
</div>
</body>
</html>
